host: 127.0.0.1
port: 4000

title: "Chimera Linux"
markdown: kramdown
highlighter: rouge

permalink: /news/:year/:month/:title.html

plugins:
  - jekyll-redirect-from

social_links:
  - ["irc", "IRC chat", "https://webchat.oftc.net/?channels=#chimera-linux"]
  - ["matrix", "Matrix chat", "https://matrix.to/#/%23chimera-linux:matrix.org"]
  - ["reddit", "Chimera Linux Reddit", "https://www.reddit.com/r/chimeralinux"]
  - ["twitter", "Chimera Linux Twitter", "https://twitter.com/chimera_linux"]

collections:
  docs:
    output: true

github_link: "https://github.com/chimera-linux"
